version: '3.8'
services: 
  web:
    build:
      context: .
    env_file: .env    
    ports:
      - "4000:4000"
    environment: 
      DATABASE_URL: "${DATABASE_URL}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      PORT: "${PORT}"
    depends_on:
      - db

  db:
    container_name: brasil-em-dados-postgres
    image: postgres:14.1-alpine
    env_file: .env    
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
  caddy:
    image: caddy:2.5.0-alpine    
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  db: 
  caddy_data:
  caddy_config: